"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2
Pentagonal      Pn=n(3n-1)/2
Hexagonal       Hn=n(2n-1)

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from sys import exit

def calcTri(n):
    return (n*(n+1))/2

pentNums = {1:1}
pentN = 1
maxPent = 1

def calcPent(n):
    newPent = (n*((3*n)-1))/2
    pentNums[newPent] = newPent
    return newPent

def isPent(n):
    global pentN, maxPent
    while maxPent < n:
        pentN += 1
        maxPent = calcPent(pentN)
    return n in pentNums


hexNums = {1:1}
hexN = 1
maxHex = 1

def calcHex(n):
    newHex = n*((2*n)-1)
    hexNums[newHex] = newHex
    return newHex

def isHex(n):
    global hexN, maxHex
    while maxHex < n:
        hexN += 1
        maxHex = calcHex(hexN)
    return n in hexNums


triN = 285
while True:
    triN += 1

    testTri = calcTri(triN)

    if isPent(testTri):
        if isHex(testTri):
            print testTri
            exit()